import PDFDocument from "pdfkit";

export interface InvoiceItem {
  description: string;
  quantity: number;
  unitPrice: number;
}

export interface InvoiceData {
  invoiceNumber: string;
  date: string;
  dueDate: string;
  from: {
    name: string;
    address: string;
    email: string;
  };
  to: {
    name: string;
    address: string;
    email: string;
  };
  items: InvoiceItem[];
  taxRate: number; // e.g. 0.11 for 11%
  notes?: string;
}

export function generateInvoicePDF(data: InvoiceData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width - 100; // margins
    const gold = "#DAA520";
    const dark = "#3E2723";
    const gray = "#666666";

    // Header bar
    doc.rect(50, 40, pageWidth, 4).fill(gold);

    // Title
    doc.fontSize(28).fillColor(dark).font("Helvetica-Bold").text("INVOICE", 50, 60);
    doc.fontSize(10).fillColor(gray).font("Helvetica").text(`#${data.invoiceNumber}`, 50, 92);

    // Dates (right-aligned)
    doc.fontSize(9).fillColor(gray);
    doc.text(`Date: ${data.date}`, 350, 65, { width: 195, align: "right" });
    doc.text(`Due: ${data.dueDate}`, 350, 80, { width: 195, align: "right" });

    // Divider
    doc.moveTo(50, 115).lineTo(50 + pageWidth, 115).strokeColor("#E0E0E0").lineWidth(1).stroke();

    // From / To
    const colY = 130;
    doc.fontSize(8).fillColor(gold).font("Helvetica-Bold").text("FROM", 50, colY);
    doc.fontSize(10).fillColor(dark).font("Helvetica-Bold").text(data.from.name, 50, colY + 14);
    doc.fontSize(9).fillColor(gray).font("Helvetica");
    doc.text(data.from.address, 50, colY + 28);
    doc.text(data.from.email, 50, colY + 42);

    doc.fontSize(8).fillColor(gold).font("Helvetica-Bold").text("BILL TO", 300, colY);
    doc.fontSize(10).fillColor(dark).font("Helvetica-Bold").text(data.to.name, 300, colY + 14);
    doc.fontSize(9).fillColor(gray).font("Helvetica");
    doc.text(data.to.address, 300, colY + 28);
    doc.text(data.to.email, 300, colY + 42);

    // Table header
    const tableTop = 210;
    doc.rect(50, tableTop, pageWidth, 24).fill("#F5F0E8");

    doc.fontSize(8).fillColor(dark).font("Helvetica-Bold");
    doc.text("DESCRIPTION", 60, tableTop + 7);
    doc.text("QTY", 340, tableTop + 7, { width: 50, align: "center" });
    doc.text("PRICE", 400, tableTop + 7, { width: 60, align: "right" });
    doc.text("AMOUNT", 470, tableTop + 7, { width: 75, align: "right" });

    // Table rows
    let y = tableTop + 30;
    doc.font("Helvetica").fontSize(9);

    for (const item of data.items) {
      const amount = item.quantity * item.unitPrice;

      if (y > 700) {
        doc.addPage();
        y = 50;
      }

      doc.fillColor(dark).text(item.description, 60, y, { width: 270 });
      doc.fillColor(gray).text(String(item.quantity), 340, y, { width: 50, align: "center" });
      doc.text(formatCurrency(item.unitPrice), 400, y, { width: 60, align: "right" });
      doc.fillColor(dark).text(formatCurrency(amount), 470, y, { width: 75, align: "right" });

      y += 22;
      doc.moveTo(60, y - 4).lineTo(540, y - 4).strokeColor("#EEEEEE").lineWidth(0.5).stroke();
    }

    // Totals
    const subtotal = data.items.reduce((sum, i) => sum + i.quantity * i.unitPrice, 0);
    const tax = subtotal * data.taxRate;
    const total = subtotal + tax;

    y += 10;
    doc.moveTo(370, y).lineTo(545, y).strokeColor("#E0E0E0").lineWidth(1).stroke();
    y += 10;

    doc.fontSize(9).fillColor(gray).font("Helvetica");
    doc.text("Subtotal", 370, y, { width: 95, align: "right" });
    doc.fillColor(dark).text(formatCurrency(subtotal), 470, y, { width: 75, align: "right" });

    y += 18;
    doc.fillColor(gray).text(`Tax (${(data.taxRate * 100).toFixed(0)}%)`, 370, y, { width: 95, align: "right" });
    doc.fillColor(dark).text(formatCurrency(tax), 470, y, { width: 75, align: "right" });

    y += 22;
    doc.rect(370, y - 4, 175, 26).fill("#F5F0E8");
    doc.fontSize(11).fillColor(dark).font("Helvetica-Bold");
    doc.text("TOTAL", 380, y + 2, { width: 85, align: "right" });
    doc.fillColor(gold).text(formatCurrency(total), 470, y + 2, { width: 75, align: "right" });

    // Notes
    if (data.notes) {
      y += 50;
      doc.fontSize(8).fillColor(gold).font("Helvetica-Bold").text("NOTES", 50, y);
      doc.fontSize(9).fillColor(gray).font("Helvetica").text(data.notes, 50, y + 14, { width: 300 });
    }

    // Footer
    doc.fontSize(8).fillColor("#BCAAA4").font("Helvetica");
    doc.text("Generated by Punakawan Minion System", 50, 770, { width: pageWidth, align: "center" });
    doc.rect(50, 790, pageWidth, 3).fill(gold);

    doc.end();
  });
}

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", minimumFractionDigits: 0 }).format(amount);
}

/** Example invoice data for testing */
export function getExampleInvoiceData(): InvoiceData {
  return {
    invoiceNumber: "INV-2026-0401",
    date: "1 April 2026",
    dueDate: "30 April 2026",
    from: {
      name: "PT Punakawan Digital",
      address: "Jl. Wayang No. 42, Jakarta Selatan 12345",
      email: "billing@punakawan.dev",
    },
    to: {
      name: "PT Nusantara Tech",
      address: "Jl. Merdeka Barat No. 10, Jakarta Pusat 10110",
      email: "finance@nusantech.co.id",
    },
    items: [
      { description: "AI Agent Development - Semar Module", quantity: 1, unitPrice: 25000000 },
      { description: "AI Agent Development - Gareng Module", quantity: 1, unitPrice: 20000000 },
      { description: "3D Visualization Dashboard", quantity: 1, unitPrice: 15000000 },
      { description: "Socket.IO Real-time Integration", quantity: 1, unitPrice: 8000000 },
      { description: "Monthly Cloud Hosting (3 months)", quantity: 3, unitPrice: 2500000 },
    ],
    taxRate: 0.11,
    notes: "Payment via bank transfer ke BCA 123-456-7890 a/n PT Punakawan Digital.\nTerms: Net 30 days.",
  };
}
